export const mockStats = {
  trackedObjects: 18732,
  trackedObjectsToday: 231,
  criticalRisks: 12,
  criticalRisksToday: 5,
  activeSatellites: 4387,
  activeSatellitesToday: 42,
  debris: 14345,
  debrisToday: 189,
  overallRisk: 26,
};

export const mockAlerts = [
  {
    id: 1,
    type: 'critical',
    title: 'Risco crítico',
    object1: 'STARLINK-2031',
    object2: 'DEBRIS-4487',
    time: '2h 34m',
    status: 'Aberta',
    probability: 4.7,
    timeToEvent: '2h 34m',
    minDistance: '1,2 km',
    aiSuggestion: 'Alterar órbita em 0,4° para reduzir o risco.',
    riskReduction: 73,
  },
  {
    id: 2,
    type: 'moderate',
    title: 'Risco moderado',
    object1: 'COSMOS-1408',
    object2: 'DEBRIS-7821',
    time: '5h 12m',
    status: 'Monitorando',
    probability: 2.1,
    timeToEvent: '5h 12m',
    minDistance: '3,8 km',
    aiSuggestion: 'Monitoramento contínuo recomendado.',
    riskReduction: 45,
  },
  {
    id: 3,
    type: 'elevated',
    title: 'Risco elevado',
    object1: 'IRIDIUM-33',
    object2: 'DEBRIS-1953',
    time: '7h 45m',
    status: 'Resolvida',
    probability: 3.2,
    timeToEvent: '7h 45m',
    minDistance: '2,1 km',
    aiSuggestion: 'Manobra de desvio executada com sucesso.',
    riskReduction: 95,
  },
  {
    id: 4,
    type: 'low',
    title: 'Risco baixo',
    object1: 'SENTINEL-1A',
    object2: 'DEBRIS-8832',
    time: '12h 15m',
    status: 'Encerrada',
    probability: 0.8,
    timeToEvent: '12h 15m',
    minDistance: '8,4 km',
    aiSuggestion: 'Sem ação necessária.',
    riskReduction: 20,
  },
];

export const mockSatellite = {
  name: 'STARLINK-2031',
  type: 'SATÉLITE ATIVO',
  noradId: '44274',
  operator: 'SpaceX',
  country: '🇺🇸 Estados Unidos',
  satelliteType: 'Comunicação',
  launch: '07/03/2023',
  mass: '260 kg',
  altitude: '550 km',
  velocity: '7,59 km/s',
  inclination: '53,2°',
  collisionRisk: 4.7,
};

export const mockNotifications = [
  {
    id: 1,
    type: 'critical',
    title: 'Alerta crítico',
    message: 'Risco de colisão detectado entre STARLINK-2031 e DEBRIS-4487.',
    time: 'Agora',
    read: false,
  },
  {
    id: 2,
    type: 'moderate',
    title: 'Alerta moderado',
    message: 'COSMOS-1408 em aproximação com DEBRIS-7821.',
    time: '18 min',
    read: false,
  },
  {
    id: 3,
    type: 'info',
    title: 'Atualização de órbita',
    message: 'Novos dados disponíveis para 5 objetos monitorados.',
    time: '1 h',
    read: true,
  },
  {
    id: 4,
    type: 'system',
    title: 'Sistema',
    message: 'Relatório diário gerado com sucesso.',
    time: '2 h',
    read: true,
  },
];

export const mockOccurrences = [
  {
    id: '#10234',
    type: 'Aproximação crítica',
    object1: 'STARLINK-2031',
    object2: 'DEBRIS-4487',
    probability: '4,7%',
    timeEstimated: '2h 34m',
    registeredBy: 'Operador Lucas',
    date: '20/05/2024 14:32',
    status: 'critical',
    actions: [
      { time: '14:33', action: 'Monitoramento intensificado', by: 'Operador Lucas' },
      { time: '14:34', action: 'Alerta enviado a operadores', by: 'Sistema' },
      { time: '14:35', action: 'Sugestão de desvio gerada', by: 'IA BlueOrbit' },
    ],
  },
];

export const riskDistribution = [
  { name: 'Crítico', value: 12, color: '#FF3B3B', pct: 6 },
  { name: 'Elevado', value: 48, color: '#FF8C00', pct: 26 },
  { name: 'Moderado', value: 120, color: '#FFD700', pct: 65 },
  { name: 'Baixo', value: 1852, color: '#00FF88', pct: 80 },
];
